### ISSUE TITLE
Digits werden nicht erkannt 

### ISSUE THREAD

**Issue by falke1987** [jomjol/water-meter-measurement-system#1]
![Screenshot_20210404-212950_Chrome](https://user-images.githubusercontent.com/46383371/113519688-1844f880-958e-11eb-8768-eacef3b65cee.jpg)

Hallo habe leider eine etwas andere wasseruhr, die nicht richtig erkannt wird. Könnten Sie evtl ihre KI nachtrainieren?

**Comment by jomjol** [comment]
EDIT: sehe gerade, dass das ja noch der alte Issue mit dem Docker Image ist. Inzwischen gibt es ein deutlich besseres System, was ganz ohne Docker funktioniert: https://github.com/jomjol/AI-on-the-edge-device

Die Entwicklung der Docker-Version wurde eingestellt. Dort laufen auch die inzwischen weiterentwickelten CNN-Files nicht mehr. Falls du auf die all-in-once Lösung AI-on-the-edge wechselst, dann kann ich auch deine Ziffer mit auf nehmen. 

Dann gilt:

- Kann ich gerne mit aufnehmen. Dazu bitte das Logging einschalten und dann jeweils pro schwarzer und roter Ziffer (0..9) 2-3 Bilder sammeln und zusenden.
- Die schwarzen Ziffern und die erste Rote ist kein Problem. Bei der zweiten roten Ziffer kommt es auf einen Versuch an. Die letzte ist stark verzehrt und wird nicht funktionieren.

**Comment by falke1987** [comment]
[20210406.zip](https://github.com/jomjol/water-meter-measurement-system/files/6407506/20210406.zip)
[20210410.zip](https://github.com/jomjol/water-meter-measurement-system/files/6407507/20210410.zip)
[20210414.zip](https://github.com/jomjol/water-meter-measurement-system/files/6407508/20210414.zip)
[Uploading 20210418.zip…]()
[Uploading 20210422.zip…]()
[Uploading 20210426.zip…]()
[Uploading 20210430.zip…]()
[Uploading 20210407.zip…]()
[Uploading 20210411.zip…]()
[Uploading 20210417.zip…]()
[Uploading 20210421.zip…]()
[Uploading 20210427.zip…]()
[Uploading 20210429.zip…]()

**Comment by falke1987** [comment]
Hallo Jomjol,

hatte mal ein paar Bilder mitgeloggt :-)

**Comment by jomjol** [comment]
Hi @falke1987,

das ist gut gemeint :-), kann ich aber so nicht verarbeiten. Du müsstest bitte pro Ziffer (0..9) ca 2-3 repräsentative Bilder heraussuchen und nur dies hochladen.

Danke und Gruß,
  jomjol

**Comment by falke1987** [comment]
Anbei nun sortierte Daten 😊

**Comment by falke1987** [comment]
Hallo Jomjol,

anbei einige sortierte Files.

[s2.zip](https://github.com/jomjol/water-meter-measurement-system/files/6538968/s2.zip)
[s3.zip](https://github.com/jomjol/water-meter-measurement-system/files/6538969/s3.zip)
[s4.zip](https://github.com/jomjol/water-meter-measurement-system/files/6538971/s4.zip)
[s5.zip](https://github.com/jomjol/water-meter-measurement-system/files/6538972/s5.zip)
[s6.zip](https://github.com/jomjol/water-meter-measurement-system/files/6538973/s6.zip)
[s7.zip](https://github.com/jomjol/water-meter-measurement-system/files/6538974/s7.zip)
[s8.zip](https://github.com/jomjol/water-meter-measurement-system/files/6538975/s8.zip)
[s9.zip](https://github.com/jomjol/water-meter-measurement-system/files/6538976/s9.zip)
[r0.zip](https://github.com/jomjol/water-meter-measurement-system/files/6538978/r0.zip)
[r1.zip](https://github.com/jomjol/water-meter-measurement-system/files/6538979/r1.zip)
[r2.zip](https://github.com/jomjol/water-meter-measurement-system/files/6538981/r2.zip)
[r3.zip](https://github.com/jomjol/water-meter-measurement-system/files/6538983/r3.zip)
[r4.zip](https://github.com/jomjol/water-meter-measurement-system/files/6538985/r4.zip)
[r5.zip](https://github.com/jomjol/water-meter-measurement-system/files/6538986/r5.zip)
[r6.zip](https://github.com/jomjol/water-meter-measurement-system/files/6538988/r6.zip)
[r7.zip](https://github.com/jomjol/water-meter-measurement-system/files/6538990/r7.zip)
[r8.zip](https://github.com/jomjol/water-meter-measurement-system/files/6538991/r8.zip)
[r9.zip](https://github.com/jomjol/water-meter-measurement-system/files/6538993/r9.zip)
[s0.zip](https://github.com/jomjol/water-meter-measurement-system/files/6538995/s0.zip)
[s1.zip](https://github.com/jomjol/water-meter-measurement-system/files/6538996/s1.zip)

**Comment by jomjol** [comment]
Hi,
das sind ja immer noch einige Hundert Bilder. Kannst du mir bitte ca 2-3 Bild je Ziffer, also in Summe 20-30 Bilder insgesamt raussortieren?
Danke und Gruß,
  jomjol

**Comment by falke1987** [comment]
[0_9.zip](https://github.com/jomjol/water-meter-measurement-system/files/6553584/0_9.zip)

**Comment by jomjol** [comment]
Nehme die Ziffern mit auf. Da sind einige dabei, die sehr viel Reflexionen haben oder nur halb drauf sind. Die werde ich aussortieren. Wenn du die auch trainiert brauchst, würde ich empfehlen, ein eigenes CNN-File anzulegen.

**Comment by jomjol** [comment]
Probier mal diese tflite: https://github.com/jomjol/neural-network-digital-counter-readout/blob/master/dig0870s3.tflite

**Comment by jomjol** [comment]
Repository wird archiviert.
